version: "3"

services:
  database:
    container_name: mongo
    build:
      context: ./mongo
      dockerfile: ./Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PWD}
    volumes:
      - ./volumes/mongo:/data/db
    ports:
      - 27018:27017
    networks:
      - aimet-test-network

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_USER}:${MONGO_INITDB_PWD}@database:27017/${MONGO_INITDB_DATABASE}?authSource=${MONGO_INITDB_DATABASE}
      MONGO_DBNAME: ${MONGO_INITDB_DATABASE}
      REDIS_URI: redis:6379
      # TODO: change to release mode for improve performance (use custom logger)
      GIN_MODE: debug
    # restart: always
    depends_on:
      - database
    networks:
      - aimet-test-network

  redis:
    container_name: redis
    image: redis:6.0.9
    ports:
      - 6379:6379
    networks:
      - aimet-test-network

  gateway:
    container_name: nginx
    image: nginx:1.19.6
    environment:
      SERVER_NAME: localhost
      BACKEND_ENDPOINT: backend:8000
    restart: always
    volumes:
      - ./nginx/gateway.conf.template:/etc/nginx/conf.d/gateway.conf.template
    ports:
      - 80:80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/gateway.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - aimet-test-network

networks:
  aimet-test-network:
    name: aimet-test-network
