version: "3"

services:
  database:
    container_name: database
    build:
      context: ./mongo
      dockerfile: ./Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PWD}
    volumes:
      - ./volumes/mongo:/data/db
    ports:
      - 27018:27017
